- name: Capture installed package information for Linux hosts
  hosts: linux

  tasks:
  - name: Get the package facts from hosts
    package_facts:
      manager: auto

  - name: Display output
    debug:
      var: ansible_facts.packages

  - local_action:
      file path="~/package_facts/{{ dir }}" state=directory
  - local_action:
      module: copy
      content: "{{ ansible_facts.packages }}"
      dest: "~/package_facts/{{ dir }}/{{ inventory_hostname }}.json"
