# subman_consumed fact
- name: gather internal_subman_consumed
  raw: subscription-manager list --consumed 2>/dev/null | grep -e '^SKU' -e '^Subscription Name' | sed -n -e 's/SKU\s*.\s*//p' -e 's/Subscription Name\s*.\s*//p' | awk '{ ORS = (NR%2 ? " - " {{":"}} RS) } 1'
  register: internal_subman_consumed
  ignore_errors: yes
  become: yes
  when: 'user_has_sudo and internal_have_subscription_manager'
